# Generated by Django 4.2.7 on 2023-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_alter_likes_post_alter_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ManyToManyField(null=True, related_name='liked_post', to='socialmedia.posts'),
        ),
    ]
